matrix:
  include:
    - language: node_js
      node_js:
        - "10.15.1"
      dist: trusty
      sudo: required

#    branches:
#      only:
#      - master

      before_script:
      - cd UsersManager-FE/users-manager
      - npm install -g @angular/cli
      - npm install -g @angular-devkit/build-angular
      - npm install

      script:
      - ng build

    - language: java
      jdk:
      - openjdk8

      sudo: false # faster builds

      before_script:
      - echo "ADSDADAD"
      - pwd
      - cd ../JerseyServer_BE
      - chmod +x gradlew

      script:
      - ./gradlew clean build