language: node_js
node_js:
  - "10.15.1"
dist: trusty
sudo: required

branches:
  only:
  - master

before_script:
- npm install -g @angular/cli
- npm install -g @angular-devkit/build-angular

script:
- cd UsersManager-FE/users-manager
- ng build